# Generated by Django 5.2.2 on 2025-06-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Install_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appsflyer_id', models.CharField(max_length=255, unique=True)),
                ('advertising_id', models.CharField(max_length=255, null=True)),
                ('campaign_name', models.CharField(max_length=255, null=True)),
                ('install_time', models.DateTimeField()),
                ('install_date', models.DateField()),
                ('platform', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('device', models.CharField(max_length=255, null=True)),
                ('media_source', models.CharField(max_length=255, null=True)),
                ('inserted_time', models.DateTimeField(null=True)),
                ('is_get_data', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['campaign_name'], name='data_fetche_campaig_8b0225_idx'), models.Index(fields=['install_date'], name='data_fetche_install_57165f_idx'), models.Index(fields=['platform'], name='data_fetche_platfor_93a272_idx'), models.Index(fields=['appsflyer_id'], name='data_fetche_appsfly_cb8198_idx'), models.Index(fields=['country'], name='data_fetche_country_9130b4_idx'), models.Index(fields=['media_source'], name='data_fetche_media_s_0a8fd2_idx'), models.Index(fields=['is_get_data'], name='data_fetche_is_get__63799a_idx')],
            },
        ),
    ]
